### ISSUE TITLE
Compile in Ubuntu 22.04

### ISSUE THREAD

**Issue by hzapa** [AdelinaSolutions/app_elevenlabs_convai#3]
Hi I'm trying compile  but i have this warning. Any Clues?

hzavala@dev02:/srv/dev/app_elevenlabs_convai$ make
gcc -fPIC -Wall -shared -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -g3 -O2 -D_REENTRANT -D_GNU_SOURCE -DAST_MODULE=\"app_elevenlabs_convai\" -I/usr/include/asterisk -o app_elevenlabs_convai.so app_elevenlabs_convai.c -lasterisk -lcurl -lcjson -lwebsockets -lssl -lcrypto -lpthread
In file included from /usr/include/netinet/in.h:23,
                 from /usr/include/asterisk/network.h:41,
                 from /usr/include/asterisk/utils.h:26,
                 from /usr/include/asterisk/alertpipe.h:22,
                 from /usr/include/asterisk/channel.h:125,
                 from /usr/include/asterisk/pbx.h:26,
                 from /usr/include/asterisk/features.h:27,
                 from /usr/include/inttypes.h:25,
                 from /usr/include/asterisk/compat.h:30,
                 from /usr/include/asterisk.h:22,
                 from app_elevenlabs_convai.c:26:
/usr/include/x86_64-linux-gnu/sys/socket.h:24:14: error: expected ‘;’ before ‘typedef’
   24 | __BEGIN_DECLS
      |              ^
      |              ;
In file included from /usr/include/x86_64-linux-gnu/bits/socket.h:29,
                 from /usr/include/x86_64-linux-gnu/sys/socket.h:33:
/usr/include/x86_64-linux-gnu/sys/types.h:27:14: error: expected ‘;’ before ‘typedef’
   27 | __BEGIN_DECLS
      |              ^

**Comment by mcammilli** [comment]
Hi, I had the same problem and I solved it this way:
edit the file app_elevenlabs_convai.c and type the following text at the beginning of the file

#define AST_MODULE_SELF_SYM __internal_my_module_self

I have another error
/usr/bin/ld: cannot find -lasterisk: No such file or directory

in this case edit the file Makefile
 - delete the line ASTERISK_HEADERS = /usr/include/asterisk
 - replace the text
    LIBS = -lasterisk -lcurl -lcjson -lwebsockets -lssl -lcrypto -lpthread
    with
    LIBS = -lasteriskssl -lcurl -lcjson -lwebsockets -lssl -lcrypto -lpthread
- replace the text
   $(CC) $(CFLAGS) -I$(ASTERISK_HEADERS) -o $@ $< $(LIBS)
   with
   $(CC) $(CFLAGS) -o $@ $< $(LIBS)

**Comment by DonSosiska** [comment]
Мені допомогла ручна збірка наступною командою:

sudo gcc -o app_elevenlabs_convai.so app_elevenlabs_convai.c -shared -fPIC -pthread -I/usr/src/asterisk-22.5.2/include -I/usr/include/libxml2 -pipe -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -g3 -O3 -fno-partial-inlining -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -march=native -DAST_MODULE=\"app_elevenlabs_convai\" -lwebsockets -lcurl -lcjson -lasteriskssl -lpthread
